include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_unnecessary_containers
    - use_build_context_synchronously
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - always_declare_return_types
    - prefer_final_fields
    - sort_child_properties_last
    - curly_braces_in_flow_control_structures
    - prefer_single_quotes
